### ISSUE TITLE
browser support: explain which platform features are used by the implementation

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#100]
Explain what platform features are used by the implementation, and provide pointers to polyfills where possible.

**Comment by kenchris** [comment]
- ResizeObserver
- Demo: Web Animations

**Comment by CaptainCodeman** [comment]
I also needed an EventTarget polyfill for Safari

**Comment by domenic** [comment]
Closing as this issue was focused on the prototype implementation, whereas we're re-focusing this repository to be a web platform explainer/specification one.
