### ISSUE TITLE
Consider making the custom-element-with-template pattern even easier

### ISSUE THREAD

**Issue by domenic** [valdrinkoshi/virtual-scroller#101]
What follows is an idea that I don't think we should do right now, but we should write down and have a place to discuss, and maybe do eventually if the demand comes up a lot.

Background: [the section on using `<template>`s to automatically create the element](https://github.com/valdrinkoshi/virtual-scroller/tree/8301ce0330e04b93ea309e8832607b0fb63f6ed4#customizing-element-creation-and-updating-with-template)

The proposal is to make the custom-element-based pattern there easier. So instead of writing

```html
<virtual-scroller>
  <template>
    <contact-element sortable></contact-element>
  </template>
</virtual-scroller>

<script type="module">
  scroller.updateElement = (child, contact) => {
    child.contact = contact;
  };

  scroller.itemSource = contacts;
</script>
```

you would write something like

```html
<virtual-scroller elementproperty="contact">
  <template>
    <contact-element sortable></contact-element>
  </template>
</virtual-scroller>

<script type="module">
  scroller.itemSource = contacts;
</script>
```

Or maybe we'd just pick a default, and say that your custom element must have a property named `data` or `item` or something.

The default `updateElement` would then check to see if the appropriate data-recieving property existed, and if so, set it to the item from the ItemSource. If the property did not exist (e.g. because you were using a normal, non-custom, element), it would fall back to the current behavior of setting `textContent`.

This is fairly sugary, and just saves some typing. But if we see this pattern become one of the dominant ways to use virtual-scroller, we should consider adding it.

**Comment by bennypowers** [comment]
Picking a default would be fine, but please retain the optional `elementproperty` (or some such) attribute. There will be uses where a ready-made custom element is available, but it doesn't take the default (sensible, though arbitrary) property.

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
