### ISSUE TITLE
Add additional ItemSource demos and docs

### ISSUE THREAD

**Issue by domenic** [valdrinkoshi/virtual-scroller#106]
Right now the README only ever uses the array-based ItemSource. But the point of the abstraction is to let you go beyond that. In particular, nothing even does the `import { ItemSource } from "std:virtual-scroller"` incantation to demonstrate how that works.

https://github.com/valdrinkoshi/virtual-scroller/blob/8301ce0330e04b93ea309e8832607b0fb63f6ed4/demo/html-spec/html-spec-viewer.js#L5-L25 is a pretty good example of a custom item source. We should consider perhaps some simpler examples, of the size we could put in the README, to demonstrate the general principle without also trying to be an impressive HTML spec viewer demo.

Perhaps as part of the same effort, or perhaps separately, I think we want to show a few different useful patterns:

- How to integrate promises with ItemSource. This could be things like an ItemSource subclass that lets `item()` return a promise and then takes care of things for you, or it could just be an example with an `updateElement` which type-tests if it receives a promise and if so displays a placeholder, replacing it once it loads.
- How to have an ItemSource that always has a "one more item" at the bottom for you, which you can click on to load more data.
- An ItemSource that isn't backed by an array (even just being backed by a Set or Map would be interesting).
- ... more?

**Comment by rakina** [comment]
Closing this as the new approach does not use the ItemSource concept anymore.
