### ISSUE TITLE
Start in the middle of the list

### ISSUE THREAD

**Issue by JosephSilber** [valdrinkoshi/virtual-scroller#111]
When scrolling huge lists that are incrementally being loaded from the server, there may be a need to actually start in the middle of the list.

Should there be a way to specify that we're in the middle of the list, and allow the user to scroll _up_ to load the previous records?

**Comment by domenic** [comment]
I think this can be done using today's API. Roughly, it would be something like:

- Have your item source return dummy items "above" the desired position.
- Have your `updateChild` render those dummy items in such a way as to give the approximately right height for them.
- Immediately call `scroller.scrollToIndex(desiredIndex)`.
- Over time, as you load data from the server, replace the dummy items with the real items. Then, when the user scrolls up, they'll see the real items. (Or, you could wait to load until they're close to being visible, by using the rangechange event.)

Maybe we should have a demo showing this?

**Comment by JosephSilber** [comment]
So if I'm starting at record 1,000,000,000 then I'd have to create such a huge array (with empty elements)?

**Comment by domenic** [comment]
No, that's the beauty of the ItemSource API! It never asks you to translate indices into items until it's ready to display them.

**Comment by valdrinkoshi** [comment]
Take a look at [smoke/infinite/index.html](https://github.com/valdrinkoshi/virtual-scroller/blob/master/smoke/infinite/index.html) as an example:
```js
virtualScroller.itemSource = new ItemSource({
  getLength: () => Number.MAX_SAFE_INTEGER,
  item: (index) => index,
  key: (index) => index,
});

// Here you can add this to scroll to the middle of the scroller
// Wait for first rendering, then scroll to middle
requestAnimationFrame(() => {
  virtualScroller.scrollToIndex(virtualScroller.itemSource.length / 2);
});
```

**Comment by JosephSilber** [comment]
We're still at least loading the first set of items, no?

**Comment by domenic** [comment]
Yeah, if you do the requestAnimationFrame, it will load and render the first set first. You could also omit the requestAnimationFrame, and then it wouldn't load/render the first set of items.

**Comment by rakina** [comment]
Closing this as this seems to be solved already?
