### ISSUE TITLE
Implement <virtual-content>

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#113]
In https://github.com/valdrinkoshi/virtual-scroller/issues/72 we talked about `virtual-scroller` and `virtual-content`. This issue tracks the definition & implementation of `virtual-content`.

`<virtual-content>` auto-sizes itself according to the estimated size of the items (sets its min-width/height), and creates DOM only for the visible portion of it. It computes the portion of the viewport currently visible by listening for scroll events on the scroll parent. It can be contained in any scroll container.

**Comment by ebidel** [comment]
+100 on something that auto-sizes itself that users can just "drop in". My limited tinkering with `virtual-scroller` doesn't do what I'd expect. and it needs a bunch of configuration (sized, setting `document.rootScroller`, etc. to get right. 

My use case is an example like this, where we want to replace a portion of content with an infinite list:

![screenflow](https://user-images.githubusercontent.com/238208/41690844-4e0d83e8-74ac-11e8-8447-2a3c034dc3ee.gif)

@valdrinkoshi reduced it here: Take this example: http://jsbin.com/cucuzuh/1/edit?html,output

By setting `document.rootScroller = scroller`, the expectation is that the list will scroll within main document scroll. What happens instead is that two scroll regions are created. One for main document scrolling and another for the `virtual-scroller` overflow region. In this example, if `virtual-scroller` were to set a `min-height` with the total height of all items, the problem goes away.

**Comment by ebidel** [comment]
FWIW, the `std:virtual-list` impl currently in Chrome Canary works beautifully for this use case and sets a `min-height`. But as I understand it, that's based on an older API and things have changed.

**Comment by valdrinkoshi** [comment]
FYI did a really quick implementation of `<virtual-content>` in this branch if you want to start playing with it https://github.com/valdrinkoshi/virtual-scroller/tree/fix-113-virtual-content

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
