### ISSUE TITLE
Consider a nice way of creating a "mapping" ItemSource

### ISSUE THREAD

**Issue by domenic** [valdrinkoshi/virtual-scroller#118]
Right now if you want to have an ItemSource that converts your "model" into your "view model" you'd do something like this:

```js
scroller.itemSource = new ItemSource({
  item(index) {
    return {
      index,
      avatarURL: avatarBaseURL + contacts[index].id,
      name: contacts[index].name
    };
  },
  getLength() {
    return contacts.length;
  }
});
```

We may want to make this easier, so you could write something like

```js
scroller.itemSource = ItemSource.fromArrayWithMapping(
  contacts,
  contact => ({
    index,
    avatarURL: avatarBaseURL + contacts[index].id,
    name: contacts[index].name
  })
);
```

We should not add this now, as it gets us deep into the model/view model management world. But I wanted to note it for later, in case we see this as a common pattern, so we have something to refer to.

Also, as noted in #103, this would likely see a lot more use if we end up with [template instantiation integration](https://github.com/valdrinkoshi/virtual-scroller#relation-to-template-instantiation-proposal). Or maybe if we did something like #101.

**Comment by kenchris** [comment]
Array.from, as an inspiration also allows mapping by default as second argument

 http://exploringjs.com/es6/ch_arrays.html#sec_new-static-array-methods

**Comment by rakina** [comment]
Closing this as this is related to the old `virtual-scroller` concept that uses ItemSource. The new approach outlined in the [explainer](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md) no longer uses this concept.
