### ISSUE TITLE
Appending to ItemSource

### ISSUE THREAD

**Issue by bennypowers** [valdrinkoshi/virtual-scroller#120]
I have some functions which fetch more items near the end of the list
```js
this.onRangechange({ first, last, target: { itemSource } }) {
  return shouldFetchMore({ itemSource, last }) ? this.fetchMoreVideos() : null;
}

fetchMoreVideos() {
  const { first } = this.variables;
  const after = getLastCursor(this.data.videos.edges);
  const variables = { after, first };
  const updateQuery = (previousResult, { fetchMoreResult }) => ({
    ...previousResult,
    videos: {
      ...previousResult.videos,
      edges: [
        ...previousResult.videos.edges,
        ...fetchMoreResult.videos.edges,
      ],
    },
  });

  return this.fetchMore({ variables, updateQuery });
}

```

Where `fetchMore` in turn tells `apollo-client` to refetch the component's query with the new variables, and then update the components' data by passing the `previousResult` and `fetchMore` result through `updateQuery`.

All that works fine and dandy, however, when the new result lands in my component's `data`, the list re-renders from the start, and I lose my position in the scroller.

Could there be some way of appending items to an ItemSource without re-rendering the list?

**Comment by domenic** [comment]
Hmm, this shouldn't cause a re-render. Could you give a more complete example? I can't tell how your ItemSource is being created, or where the appending is happening, or whether you're using the key function of the ItemSource...

**Comment by domenic** [comment]
Closing this as this is related to the old virtual-scroller concept that uses ItemSource. The new approach outlined in the [explainer](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md) no longer uses this concept.
