### ISSUE TITLE
How do we handle navigating to links deep within an invisible root?

### ISSUE THREAD

**Issue by bicknellr** [valdrinkoshi/virtual-scroller#139]
One area that we need to explore with invisible DOM is how we handle navigation to an element that's inside an invisible root and would be laid out very far down in the box of that invisible root. The virtual scroller implementation here is able to scroll to an *item* but it doesn't currently handle scrolling to the actual element once the viewport has been moved to the item - should it? In general, what amount of scrolling behavior should be built in and what amount should be left to the author that has decided to use invisible DOM? If most of this behavior were left to the author to implement, what other things need to be exposed to reach parity with the browser's default behavior on pages without invisible DOM (if anything)?

cc @ojanvafai

**Comment by ojanvafai** [comment]
@domenic @rakina something for us to think through what the UX should be and what that implies about how virtual-scroller + invisible DOM should work.

**Comment by bicknellr** [comment]
Trying to recap some info from a meeting:

I think we settled on letting the browser itself scroll to the correct position assuming that it attempts to scroll only once it was finished dispatching 'activateinvisible', during which the virtual-scroller had made that element visible.

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
