### ISSUE TITLE
Api to get the item for a element and vice versa

### ISSUE THREAD

**Issue by jogibear9988** [valdrinkoshi/virtual-scroller#143]
Is there a API to get the underlying item for an element? And one to get the Element for and underlying item?

I've needed this several times when I used iron-list

**Comment by valdrinkoshi** [comment]
What would be the use case?
If you save the item on each child (e.g. as we do for `<contact-element>`), it should be as simple as:
```js
scroller.updateElement = (elem, item) => elem.item = item;
const elementForItem = (item) => scroller.children.find(elem => elem.item === item);
const itemForElement = (elem) => elem.item;
```

**Comment by valdrinkoshi** [comment]
@jogibear9988 interesting, can you provide more details? E.g. do you want to focus only when receiving the data, or programmatically trigger it when the user clicks on the element?

You could have a container-like custom element that forwards focus to the focusable child when selected.
You can as well configure its shadowRoot with delegatesFocus: true, which basically makes the element focusable and forwards the focus to the first focusable child if any. In this case you wouldn't need a selected property, but just call focus() on the container custom element, or just set an autofocus` attribute on it

**Comment by domenic** [comment]
Closing this as this is related to the old virtual-scroller concept that uses ItemSource. The new approach outlined in the [explainer](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md) no longer uses this concept.
