### ISSUE TITLE
Accessibility (A11y) and keyboard shortcuts

### ISSUE THREAD

**Issue by TheJaredWilcurt** [valdrinkoshi/virtual-scroller#146]
I'm concerned that this functionality will be built, and adopted by developers, before proper consideration is given to those with disabilities and how they interact with devices, browsers, and applications.

Scrollbars being visible and functioning as expected are very important to those with disabilities. From playing around with the [demos](https://valdrinkoshi.github.io/virtual-scroller/demo/index.html), most do not perform as expected. Clicking and dragging the scrollbar [thumb](https://www.quackit.com/pix/css/css_scrollbars_webkit.png) is very difficult as it often does not follow where the cursor is dragging. It is constantly moving, and readjusting as content loads and the layout is recalculated.

More importantly, many keyboard shortcuts seem broken in many of the demos. It seems to require a mouse click between each press of pageUp or pageDown (or spacebar and shift+spacebar). Despite this being unintuitive, it could be quite taxing for those with handicaps or using special input devices. Often times concessions for accessibility are not made on websites and in applications, but the usage of common keyboard shortcuts can be mapped to specifc buttons on input devices to fill in the gaps. So it's very important that keyboard shortcuts involving scrolling work as they normally would.

Common keyboard shortcuts used for scroll navigation:

* page up/page down
* spacebar/shift+spacebar
* up and down arrow
* left and right arrow (for horizontal navigation)
* home
* end
* tabbing to focus points (like links or form fields)
* Middle click and drag (which can be mapped to key or button presses)
* Mouse wheel scroll up/down (which can be mapped to key or button presses)

**Comment by robrez** [comment]
The problems w/ scrolling via keyboard (page up/down, arrows) seem to be limited to cases where the virtual-scroller is inside a stacking context (using a relative scroll region).

The demos that use document scrolling seem to work fine --
https://valdrinkoshi.github.io/virtual-scroller/demo/contacts/

But relative scroll regions require a re-focus (via click) --
https://valdrinkoshi.github.io/virtual-scroller/demo/scrolling.html
https://valdrinkoshi.github.io/virtual-scroller/demo/layout.html

**Comment by rakina** [comment]
The new approach for this, detailed in the [explainer](https://github.com/valdrinkoshi/virtual-scroller/blob/master/README.md) makes sure that a11y feature would work well with it, since it will keep all of the content in the DOM.

**Comment by domenic** [comment]
Closing since the current approach accounts for this, at least on the spec level that this repository is focused on. But this will be important for implementers to test when working on their implementation of the spec, and you can be sure Chrome will do so as we prototype!
