### ISSUE TITLE
Demo with folder tree

### ISSUE THREAD

**Issue by panther7** [valdrinkoshi/virtual-scroller#154]
Idea for next demo :)

![foldertree](https://user-images.githubusercontent.com/3808250/52072813-3b2a8b00-2586-11e9-963c-16dbc6e80358.png)

**Comment by rakina** [comment]
Thank you for the suggestion! We currently are trying to make this repository focus on the standards side of `virtual-scroller`, so I am closing this. See also: https://github.com/valdrinkoshi/virtual-scroller/issues/158#issuecomment-480913127. 

FYI we're going to have a separate demos repository later on, that can be used with Chromium's implementation of the new approach. Stay tuned for updates!
