### ISSUE TITLE
Current State of the Project?

### ISSUE THREAD

**Issue by jogibear9988** [valdrinkoshi/virtual-scroller#158]
What is the current State of the Project?

Is it useable already (not only in Chrome, also in FF and Safari)?

**Comment by domenic** [comment]
Hey @jogibear9988, thanks for your interest! Indeed, I can see how the state of the project is not super-clear at the moment.

The biggest problem with this repository, in our view, is that it's currently a weird mix of web platform feature explainer/spec and prototype code for our Chromium implementation. We're working to fix this in #156, by removing all prototype code (which will instead live in the Chromium source tree) and focusing entirely on the web standards angle for the proposed virtual-scroller HTML element. Then we'll do a pass through the issue tracker and close all issues related to the prototype code/demos, so we can focus on using this repository as a place to develop a web standards proposal. At that point it will likely move to the [WICG](https://www.w3.org/community/wicg/) while we develop it, before---hopefully---eventually being added to the [HTML standard](http://html.spec.whatwg.org/multipage/).

So to answer your question directly, no, this is not very usable at this point :). We need to write a spec, then convince browsers to implement it. Chrome believes this is a good idea and will invest in behind-a-flag implementations as we develop the spec proposal, and eventually an [origin trial](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md). Other browsers will hopefully participate in the standardization process as well, and implement in their own browsers.

This is a long process, but we're hopeful that with continued interest from folks like you, it'll go faster, as we'll be able to rapidly iterate on the spec and implementation and show the value of this feature on real world websites.

Hope this helps! And stay tuned over the next week for the changes to this repository, which should make it clearer.

**Comment by jogibear9988** [comment]
my problem is, what to use today?

as polymer is in maintenance mode.

**Comment by domenic** [comment]
I'm not sure what's best for your situation. We've done research into various popular virtual scroller libraries in https://github.com/domenic/infinite-list-study-group , showing the capabilities of Polymer, Angular, and WinJS on the web. We've also been working with the author of react-virtualized and react-window, as we know those are quite popular today. But in the end, the spec authors working on this repository are probably not the best people to advise you on these sorts of decisions; you'll need to do your own research.

**Comment by domenic** [comment]
OK, so, the state of the repository should be pretty clear now! We've cleaned up the contents to focus only on being a spec proposal, and the issue tracker similarly. I'll close this issue, but thanks for opening it and giving us the opportunity to clarify!

**Comment by crisward** [comment]
You may want to update this too if you can - seems to 404

https://chromestatus.com/feature/5673195159945216

**Comment by domenic** [comment]
Thanks @crisward; updated!
