### ISSUE TITLE
Changes of input items doenst cause change detection in VS 

### ISSUE THREAD

**Issue by Liork1** [valdrinkoshi/virtual-scroller#159]
Hi,

I have this implementation in my component.
When the item input value popupGamesViewModel?.popupGames is updated, I don't see the number of items in the UI updated until I start to scroll.

can you please advice?
Thanks,
Lior

```
 <virtual-scroller [items]="popupGamesViewModel?.popupGames"
                          [parentScroll]="scrollingBlock.nativeElement"
                          (update)="viewPortItems = $event"
                          id="igames-mobile-virtual-scroll"
                          [class.no-scroll]="isAnyPopupOpened" scrollOnePixel>
              <ng-template ngFor let-item [ngForOf]="viewPortItems">
                <div class="igames-mobile-slot-wrap item-wrapper">
                  <slot [slot]="item"
                        [igFavoritesGames]="popupGamesViewModel?.igFavoritesIds"
                        (updateFavoriteIgGame)="updateFavoriteGame($event)"
                        (openPopupGame)="openPopUpGame($event)">
                  </slot>
                </div>
              </ng-template>
          </virtual-scroller>
```

**Comment by domenic** [comment]
Hey! This appears to be a question about the previous prototype implementation that was in this repository. That was always meant to just be a prototype, not an officially supported library, and we're now shutting down work on it and letting this repository be focused entirely on being a proposal for a new web platform feature. So, we're closing issues related to the old prototype. See https://github.com/valdrinkoshi/virtual-scroller/issues/158#issuecomment-480913127 for a bit more detail.

Sorry if this isn't as helpful as you were hoping, but best of luck finding a solution for your app!
