### ISSUE TITLE
handle margin collapsing

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#2]
From https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing:
> The margins of adjacent siblings are collapsed (except when the latter sibling needs to be cleared past floats).

The Layout should manage this when computing positioning, so probably Repeater should provide also child margin information.

**Comment by domenic** [comment]
My take on this is that it's OK to not handle it. We have a particular special case in the HTML spec demo where lack of margin collapsing, applied to content that expects margin-collapsing, causes extra margins to appear. But for content written against virtual-scroller in the first case, this won't be an issue.

The alternative would be, I think, to add a mode that tries to do margin-collapsing for you.

@ojanvafai, any thoughts? Especially from the perspective of wanting people to use this as a general virtualization primitive for news articles etc. It does become a bit less of a transparent drop-in replacement if putting your news article in virtual-scroller and now you have double margins between all your paragraphs.

**Comment by valdrinkoshi** [comment]
It would be nice if we could allow the user to use css margin and virtual-scroller do the right thing - this should be an easy thing to do in the Layout class, as the margin information is already available.

Layout class exposes a `spacing` property, to be used as margin between items, so we could expose it in virtual-scroller. 
If we opt for that, it would allow us to avoid computing the margins when we measure too.

Another option is to expose a method that provides the size and margins for each element - childSize (as proposed in https://github.com/valdrinkoshi/virtual-scroller/issues/69), and the user would pass the size + margin information for each element.

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
