### ISSUE TITLE
toggling layout should reset secondary dimension

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#24]
Toggling the layout from vertical to horizontal should reset the minHeight on the container.
Likewise, toggling from horizontal to vertical should reset the minWidth.

**Comment by valdrinkoshi** [comment]
As a temporary workaround, the user can create a new instance of Layout with the desired direction.
`RepeatsAndScrolls` will handle the resetting of `min-width/min-height` when a new layout is set.

**Comment by domenic** [comment]
Is this an issue exposed to users of `<virtual-scroller>`, or only via the internal components? If the latter, maybe we could have a special issue label for those?

**Comment by valdrinkoshi** [comment]
It's not exposed to the virtual-scroller user. We're currently creating a new instance of Layout instead of just updating the instance property.

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
