### ISSUE TITLE
should we ship requestReset()?

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#26]
`<virtual-list>` currently exposes the `requestReset()` method as a mean to trigger a rerendering of the DOM. This is useful for users that want to keep the same `items` array instance, perform an arbitrary number of updates to it, and decide when to trigger the rerendering.

Should we expose such method?

Other possible solutions:
1) always trigger the rerendering when `items` is set
2) require the user to provide a new `items` array instance to trigger the update

If we want to keep this method, what would be a better name for it?

**Comment by domenic** [comment]
So ideally IMO we never ask the user to use requestReset() for rendering-related reasons (like animations), but always use it for data-related reasons.

**Comment by domenic** [comment]
Let's roll this into #70, since that will help realize the "always use requestReset/itemsChanged for data-related reasons" vision.
