### ISSUE TITLE
How to ship virtual-list-element.js dependencies?

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#27]
In particular `./layouts/*.js`, `./virtual-repeater.js` and `./virtual-list.js`

**Comment by domenic** [comment]
I don't think that's quite related. This is more of a question of how or whether we include the lower-level building blocks (detailed in DESIGN.md).

**Comment by jyasskin** [comment]
What do you mean by "ship"? If you just stick the files on a server, the natural module loading process will find them, but it'll take more round-trips than optimal. If you bundle just the virtual-list-element.js dependencies, they'll load in one round-trip. If you let the application author bundle virtual-list-element.js and its dependencies with the application itself, they might load in 0 extra round-trips.

**Comment by domenic** [comment]
I think the question is much more fundamental than that; sorry about the ambiguous OP.

Right now the plan is to only include `<virtual-list>` in the layered API. But, maybe we should include the various building blocks---currently named `VirtualRepeater`, `Layout`, and `RepeatsAndScrolls`, and currently located in the files listed in the OP.

The OP's question is: should we include them? If so, what exact APIs are good to expose?

**Comment by jyasskin** [comment]
Yep, Web Packaging says nothing about the public API you should expose. :)

**Comment by kenchris** [comment]
Yeah, I guess the issue title wasn't all that clear :-)

**Comment by domenic** [comment]
Given the API shakeups, let's close this for now, and revisit the mechanics of exposing the public API when we have a better idea what the public API actually is :)
