### ISSUE TITLE
<virtual-list> styled with `contain: strict`

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#37]
Currently `<virtual-list>` styles its host with `contain: strict` to help the browser reduce the layout/paint/style computations.

One of the drawbacks is that content intentionally overflowing outside the virtual-list will be clipped, e.g.
```html
<style>
  virtual-list {
    width: 200px;
  }
  .tooltip {
    position: absolute;
    top: 0;
    left: 180px;
  }
</style>
<virtual-list id="list"></virtual-list>
<script>
  list.newChild = () => {
    const child = document.createElement('div');
    child.innerHTML =`
     <span>Hello world!</span>
     <span class="tooltip">custom tooltip</span>`;
   return child;
  };
  list.items = new Array(100);
</script>
```
The user can still override the default value via css, e.g. `virtual-list { contain: none; }`, and we could also expose a css custom property.

Before doing that, is it worth for `<virtual-list>` to set this default style?

**Comment by ojanvafai** [comment]
This seems like the right default to me as we believe it will open up opportunities for better performance in browser rendering, but browsers aren't there yet. Still, we don't want people to depend on overflowing if we can avoid it.

It's important that people be able to override it.

I'm also a little surprised to see that containment is on the list itself and not the individual list items.

**Comment by valdrinkoshi** [comment]
The reason why containment is not currently done on the items is to support use cases like a custom dropdown within a list item, which will surely overflow, e.g. see http://jsbin.com/heyiwed/2/edit?html,output

To be honest that use case is already hosed, as even if we don't do containment, the fact that we're creating a stacking context for each item DOM breaks the z-index for the dropdowns

| w/o containment | contain: content |
|----------|--------|
| <img width="173" alt="screen shot 2018-04-27 at 3 51 52 pm" src="https://user-images.githubusercontent.com/6173664/39388198-25af11d0-4a33-11e8-9d19-d4f920090036.png"> | <img width="176" alt="screen shot 2018-04-27 at 3 51 40 pm" src="https://user-images.githubusercontent.com/6173664/39388199-25c450ae-4a33-11e8-9359-e05c3d198798.png"> |

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
