### ISSUE TITLE
use IntersectionObserver?

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#54]
`VirtualList` computes the viewport manually by diffing the scrollTarget bounds with the container bounds. We use `getBoundingClientRect()` to get scroll position and size, so we force layout.
We might be able to use [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to get the scroll position info w/o causing relayout.
For the size, we can rely on ResizeObserver (#16)

**Comment by domenic** [comment]
Is this still the plan? I think @flackr's virtual list was based on IntersectionObserver, right?

**Comment by domenic** [comment]
The virtual-content branch is currently doing this :)
