### ISSUE TITLE
let's discuss render timing expectations

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#78]
_Context: see [this note](https://github.com/valdrinkoshi/virtual-scroller/pull/16#discussion_r189331076) from @atotic on ResizeObserver timing (rAF, then ResizeObserver, then Paint)_

Currently we batch rendering with a rAF. This means that a user can expect to have the `virtual-scroller` rendered by the next frame.

Is it reasonable to explicitly say this
> expect `virtual-scroller` to be done rendering by the next rAF (1)
```js
vscroller.totalItems = 10;
requestAnimationFrame(() => {
  console.log(vscroller.childElementCount);
});
```

or should we instead say 
> expect `virtual-scroller` to be done rendering by the next paint (2)
```js
vscroller.totalItems = 10;
requestAnimationFrame(() => 
  Promise.resolve().then(() => {
    console.log(vscroller.childElementCount);
  })
);
```
With option (1) we're currently obliged to force reflow on the container, as ResizeObserver callback is invoked after the rAF callback.

Option (2) would allow us to use the ResizeObserver timing as signal to render synchronously. I don't know if there is a "blessed way" for having an _afterPaint_ callback, so we could expose a `afterNextRender` promise in `virtual-scroller` to be used exactly for this:
```js
vscroller.totalItems = 10;
vscroller.afterNextRender().then(() => {
  console.log(vscroller.childElementCount);
});
```

@domenic WDYT?

**Comment by domenic** [comment]
(1) seems more predictable and better to me. I'd stick with (1), unless we find that the performance advantages of doing (2) are significant? So we'd want to quantify this with some traces on the various demo pages, including ideally on slow mobile devices.

**Comment by atotic** [comment]
Discussed with valdrinkoshi on Hangouts. You might be able to guarantee immediate paint (before next rAF). Only gotcha here is long relayout before paint. If you want to get fancy, you could monitor for this condition, and do next rAF paint if layout takes too long, immediate otherwise.

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
