### ISSUE TITLE
different template engines (lit-html/preact)

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#81]
`<virtual-scroller>` expects `new/update/recycleChild` methods to return/handle `Element` nodes, and `VirtualRepeater` relies on `Element` native APIs to append/move/remove/measure these.

Other templating engines like lit-html or preact create different types of instances for their rendering purposes, e.g. lit-html deals with `TemplateResult`s, preact with `VNodes`, and their `render()` methods know how to convert these into DOM to be stamped in a container.
 
The current `virtual-scroller` makes it confusing for the user to deal with both `TemplateResults/VNodes` and `Elements`. E.g. this is the most ergonomic way to use `virtual-scroller` with lit-html/preact http://jsbin.com/secetor/1/edit?html,output
```js
import './virtual-scroller-element.js';
import {html, render as litRender} from './node_modules/lit-html/lib/lit-extended.js';
import {createElement, render as preactRender} from './node_modules/preact/dist/preact.esm.js';

const wrapper = 'div';
const totalItems = 100;

/* -- raw -- */
const rawScroller = (totalItems) => {
  const scroller = document.createElement('virtual-scroller');
  scroller.newChild = (i) => document.createElement(wrapper);
  scroller.updateChild = (el, i) => el.textContent = `index ${i}`;
  scroller.totalItems = totalItems;
  return scroller;
};
const rawRender = (elem, container) => container.append(elem);

rawRender(rawScroller(totalItems), rawContainer);

/* -- lit-html -- */
const litScroller = (totalItems) => html`
    <virtual-scroller
      newChild="${() => document.createElement(wrapper)}"
      updateChild="${(el, i) => litRender(html`index ${i}`, el)}"
      totalItems="${totalItems}"></virtual-scroller>`;

litRender(litScroller(totalItems), litContainer);

/* -- preact -- */
const preactScroller = (totalItems) => createElement(
    'virtual-scroller', {
      newChild: () => document.createElement(wrapper),
      updateChild: (el, i) => el.textContent = `index ${i}`,
      totalItems,
  });

preactRender(preactScroller(totalItems), preactContainer);
```

How can we make this more ergonomic for the lit-html and preact users? How would that look like?

Both lit-html and preact need to generate instances that are not Element nodes, and to handle how these instances are rendered via their specific `render()` method, whereas `virtual-scroller` needs to keep track of the created children, and to append/move/remove/measure them.

@justinfagnani @developit @domenic WDYT?

**Comment by valdrinkoshi** [comment]
We could suggest to create new custom elements that extend `VirtualScrollerElement` and handle the template engine specific instances. Here's a stab of how it would look like to use:

```js
/*-- lit-html --*/
const litScroller = (totalItems) => html`
    <lit-scroller
      childTemplate="${(i) => html`<div>index ${i}</div>`}"
      totalItems="${totalItems}"></lit-scroller>`;

litRender(litScroller(totalItems), litContainer);

/* -- preact -- */
const preactScroller = (totalItems) => createElement(
    'preact-scroller', {
      childTemplate: (i) => createElement('div', {textContent: `index ${i}`}),
      totalItems,
  });

preactRender(preactScroller(totalItems), preactContainer);
```

**Comment by kenchris** [comment]
I think it seems more natural in a lit/web components world to have the content template be a child/slot of the <lit-scroller>, but I don't know how that would work.

The above seems a bit messy, and then I think I would rather prefer a lit directive instead - but I do see the point of actually declaring the lit-scroller element so that it is easily configurable and stylable.

**Comment by domenic** [comment]
In general I think your custom element versions are pretty solid. I wish I had more to offer than just "that sounds good", but that's mostly it :).

I think we should spin up a separate thread to discuss a default newChild value. It seems pretty appealing to me.

**Comment by developit** [comment]
Just a note - might be more idiomatic to use a component for the VDOM interface:

```js
const PreactScroller = ({ totalItems, children }) => createElement('preact-scroller', {
  childTemplate: children[0]
  totalItems
});

preactRender(createElement(
  PreactScroller,
  { totalItems },
  i => createElement('div', null, `index ${i}`)
), preactContainer);
```

**Comment by rakina** [comment]
Closing this as this is related to the `virtual-scroller` prototype implementation and we intend to make this repository focus on the standards side of it.
