### ISSUE TITLE
Interesting interaction with browser chrome on android

### ISSUE THREAD

**Issue by kenchris** [valdrinkoshi/virtual-scroller#82]
The rendering of the HTML spec is only sized to the viewport of the browser when the header (chrome with address bar) is visible

![image](https://user-images.githubusercontent.com/1101339/40433315-0867e696-5eac-11e8-9bc7-04edfaf43411.png)

**Comment by valdrinkoshi** [comment]
Are you testing with Experimental features on? that enables document.rootScroller

The `<html-spec-viewer>` is position: fixed; top: 0, but the top doesn't seem to be updated to be updated as the URL bar animates up/down 
![screenshot_20180523-112959](https://user-images.githubusercontent.com/6173664/40444126-50ea334e-5e7d-11e8-8076-e6869ed18d2b.png)

**Comment by valdrinkoshi** [comment]
Here a simpler repro https://jsbin.com/lubesedoyo/1/quiet (code https://jsbin.com/lubesedoyo/1/edit?html)

Looks like a document.rootScroller bug

**Comment by kenchris** [comment]
@bokand might know more then

**Comment by bokand** [comment]
Thanks! Filed [846322](https://crbug.com/846322) to track this. I'll take a look shortly.
