### ISSUE TITLE
HTML spec viewer is broken after last update

### ISSUE THREAD

**Issue by kenchris** [valdrinkoshi/virtual-scroller#91]
Check screenshot:

![screenshot 2018-06-07 at 16 47 28](https://user-images.githubusercontent.com/1101339/41107386-8b52a4c0-6a72-11e8-906b-b4c04d643031.png)

**Comment by valdrinkoshi** [comment]
lol 😆

**Comment by valdrinkoshi** [comment]
Got fixed in #83 👌
